<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="HP Unified Functional Testing" productVer="12.52" os="Windows 7" host="IDELIVER8"><DocLocation><![CDATA[F:\Cleartrip\Script]]></DocLocation></General>
<Doc rID="T1"   productName= "HP Unified Functional Testing"  >
<DName><![CDATA[Script]]></DName>
<Res><![CDATA[Res1]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="20" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<Action rID="T3">
<AName><![CDATA[Action1]]></AName>
<Step rID="T4">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Transaction "Login" started.]]></Details>
<Time><![CDATA[17-Oct-16 - 20:36:59]]></Time>
<TimeTick>1476716819</TimeTick>
<NodeArgs eType="Transaction" icon="22" nRep="7" nType="Start Transaction" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[17-Oct-16 - 20:37:01]]></Time>
<TimeTick>1476716821</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Run "chrome",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "chrome",1]]></Details>
<Time><![CDATA[17-Oct-16 - 20:37:01]]></Time>
<TimeTick>1476716821</TimeTick>
<NodeArgs eType="Replay" icon="23" nRep="11" status="Passed" >
<Disp><![CDATA[Run "chrome",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="23" nRep="10" status="Passed" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Transaction "Login" ended with "Pass" status (Total Duration: 4.7437 sec).]]></Details>
<Time><![CDATA[17-Oct-16 - 20:37:04]]></Time>
<TimeTick>1476716824</TimeTick>
<NodeArgs eType="Transaction" icon="24" nRep="12" nType="End Transaction" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj ><![CDATA[Step-1]]></Obj>
<Details ><![CDATA[Home page is open]]></Details>
<Time><![CDATA[17-Oct-16 - 20:37:04]]></Time>
<TimeTick>1476716824</TimeTick>
<NodeArgs eType="User" icon="25" nRep="13" status="Passed" >
<Disp><![CDATA[Step-1]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf1.xml]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Cleartrip - Flights, Hotels,]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[17-Oct-16 - 20:37:08]]></Time>
<TimeTick>1476716828</TimeTick>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA["Cleartrip - Flights, Hotels,"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not unique (6 objects found)</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>micclass=Browser<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (6 objects found)&nbsp;</FONT></u><br>
micclass=Browser<br><br><FONT face=Verdana size=2><u>Optional filter properties</FONT></u><br>
name=Cleartrip - Flights, Hotels, Local, Trains, Packages<SPAN class=passed> (Used</SPAN>, 1 matches)</SPAN><br>title=Cleartrip - Flights, Hotels, Local, Trains, Packages<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>openurl=https://www.cleartrip.com<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>opentitle=Cleartrip - Flights, Hotels, Local, Trains, Packages<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>openedbytestingtool=-1<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>number of tabs=3<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>]]></Details>
<Time><![CDATA[17-Oct-16 - 20:37:08]]></Time>
<TimeTick>1476716828</TimeTick>
<NodeArgs eType="Replay" icon="27" nRep="15" Source="Action1" SourceLine="-1" >
<Disp><![CDATA["Cleartrip - Flights, Hotels,"- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[Cleartrip - Flights, Hotels,]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[17-Oct-16 - 20:37:09]]></Time>
<TimeTick>1476716829</TimeTick>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Cleartrip - Flights, Hotels,.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[17-Oct-16 - 20:37:09]]></Time>
<TimeTick>1476716829</TimeTick>
<NodeArgs eType="Replay" icon="28" nRep="18" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Cleartrip - Flights, Hotels,.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[Flight_details]]></Obj>
<Details plainTxt="False" ><![CDATA[Transaction "Flight_details" started.]]></Details>
<Time><![CDATA[17-Oct-16 - 20:37:09]]></Time>
<TimeTick>1476716829</TimeTick>
<NodeArgs eType="Transaction" icon="22" nRep="19" nType="Start Transaction" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Flight_details]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[trip_type.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[17-Oct-16 - 20:37:09]]></Time>
<TimeTick>1476716829</TimeTick>
<NodeArgs eType="Replay" icon="29" nRep="21" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[trip_type.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[trip_type.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Oneway"]]></Details>
<Time><![CDATA[17-Oct-16 - 20:37:09]]></Time>
<TimeTick>1476716829</TimeTick>
<NodeArgs eType="Replay" icon="29" nRep="24" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[trip_type.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[origin.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[17-Oct-16 - 20:37:09]]></Time>
<TimeTick>1476716829</TimeTick>
<NodeArgs eType="Replay" icon="30" nRep="26" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[origin.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[origin.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Nagpur"]]></Details>
<Time><![CDATA[17-Oct-16 - 20:37:09]]></Time>
<TimeTick>1476716829</TimeTick>
<NodeArgs eType="Replay" icon="30" nRep="29" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[origin.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[destination.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[17-Oct-16 - 20:37:09]]></Time>
<TimeTick>1476716829</TimeTick>
<NodeArgs eType="Replay" icon="30" nRep="31" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[destination.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[destination.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Mumbai"]]></Details>
<Time><![CDATA[17-Oct-16 - 20:37:09]]></Time>
<TimeTick>1476716829</TimeTick>
<NodeArgs eType="Replay" icon="30" nRep="34" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[destination.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[Cal.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[17-Oct-16 - 20:37:09]]></Time>
<TimeTick>1476716829</TimeTick>
<NodeArgs eType="Replay" icon="31" nRep="37" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Cal.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="28" nRep="17" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Cleartrip - Flights, Hotels,]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="26" nRep="14" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Cleartrip - Flights, Hotels,]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[Cleartrip | Book your]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[17-Oct-16 - 20:37:10]]></Time>
<TimeTick>1476716830</TimeTick>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA["Cleartrip | Book your"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not unique (6 objects found)</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>micclass=Browser<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (6 objects found)&nbsp;</FONT></u><br>
micclass=Browser<br><br><FONT face=Verdana size=2><u>Optional filter properties</FONT></u><br>
name=Cleartrip | Book your flight securely in simple steps<SPAN class=passed> (Used</SPAN>, 1 matches)</SPAN><br>title=Cleartrip | Book your flight securely in simple steps<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>openurl=https://www.cleartrip.com<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>opentitle=Cleartrip - Flights, Hotels, Local, Trains, Packages<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>openedbytestingtool=-1<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>number of tabs=4<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>]]></Details>
<Time><![CDATA[17-Oct-16 - 20:37:10]]></Time>
<TimeTick>1476716830</TimeTick>
<NodeArgs eType="Replay" icon="27" nRep="39" Source="Action1" SourceLine="-1" >
<Disp><![CDATA["Cleartrip | Book your"- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[Cleartrip - Flights, Hotels,]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[17-Oct-16 - 20:37:30]]></Time>
<TimeTick>1476716850</TimeTick>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[October 2016.GetROProperty "innertext"]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[17-Oct-16 - 20:37:30]]></Time>
<TimeTick>1476716850</TimeTick>
<NodeArgs eType="Replay" icon="31" nRep="77" status="Warning" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[October 2016.GetROProperty "innertext"]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[October 2016]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object "October 2016" (of class WebElement).
Verify that this object's properties match an object currently displayed in your application.]]></Details>
<Time><![CDATA[17-Oct-16 - 20:37:30]]></Time>
<TimeTick>1476716850</TimeTick>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[October 2016]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>miccommentproperty = <br>Mercury Class = WebElement<br>Index = 1<br>Html Tag = DIV<br>_xpath = //DIV/DIV[normalize-space()="October 2016"]/DIV[1]<br>|Visible = -1<br>innertext = \w+ 2016<br>Html Id = <br>DHTML Class = title<br>]]></Details>
<Time><![CDATA[17-Oct-16 - 20:37:30]]></Time>
<TimeTick>1476716850</TimeTick>
<NodeArgs eType="Replay" icon="32" nRep="79" status="Warning" nType="Description" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[October 2016]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="31" nRep="78" status="Failed" nType="Run Error" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[October 2016]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="28" nRep="76" status="Failed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Cleartrip - Flights, Hotels,]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="26" nRep="38" status="Failed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Cleartrip | Book your]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[Cleartrip | Book your]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[17-Oct-16 - 20:37:31]]></Time>
<TimeTick>1476716851</TimeTick>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object &quot;October 2016&quot; (of class WebElement).<BR/>Verify that this object's properties match an object currently displayed in your application.<BR/>Line (65): &quot;mont_name = Browser(&quot;Cleartrip | Book your&quot;).Page(&quot;Cleartrip - Flights, Hotels,&quot;).WebElement(&quot;October 2016&quot;).GetROProperty(&quot;innertext&quot;)&quot;. ]]></Details>
<Time><![CDATA[17-Oct-16 - 20:37:31]]></Time>
<TimeTick>1476716851</TimeTick>
<NodeArgs eType="Replay" icon="32" nRep="81" status="Failed" Source="Action1" SourceLine="64" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="26" nRep="80" status="Failed" Source="Action1" SourceLine="64" >
<Disp><![CDATA[Cleartrip | Book your]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Subscript out of range: '[number: 0]'<BR/>Line (67): &quot;month_name = trim(mont_name1(0))&quot;. ]]></Details>
<Time><![CDATA[17-Oct-16 - 20:37:31]]></Time>
<TimeTick>1476716851</TimeTick>
<NodeArgs eType="Replay" icon="32" nRep="82" status="Failed" Source="Action1" SourceLine="66" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[Cleartrip - Flights, Hotels,]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[17-Oct-16 - 20:37:31]]></Time>
<TimeTick>1476716851</TimeTick>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[Cleartrip - Flights, Hotels,]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[17-Oct-16 - 20:37:31]]></Time>
<TimeTick>1476716851</TimeTick>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA["M":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[GetRowWithCellText]]></Details>
<Time><![CDATA[17-Oct-16 - 20:37:31]]></Time>
<TimeTick>1476716851</TimeTick>
<NodeArgs eType="General" icon="33" nRep="86" status="Passed" >
<Disp><![CDATA["M":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA["M":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[ColumnCount]]></Details>
<Time><![CDATA[17-Oct-16 - 20:37:31]]></Time>
<TimeTick>1476716851</TimeTick>
<NodeArgs eType="General" icon="33" nRep="88" >
<Disp><![CDATA["M":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA["M":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[17-Oct-16 - 20:37:31]]></Time>
<TimeTick>1476716851</TimeTick>
<NodeArgs eType="General" icon="33" nRep="90" >
<Disp><![CDATA["M":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA["M":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[17-Oct-16 - 20:37:31]]></Time>
<TimeTick>1476716851</TimeTick>
<NodeArgs eType="General" icon="33" nRep="92" >
<Disp><![CDATA["M":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA["M":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[17-Oct-16 - 20:37:31]]></Time>
<TimeTick>1476716851</TimeTick>
<NodeArgs eType="General" icon="33" nRep="94" >
<Disp><![CDATA["M":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA["M":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[17-Oct-16 - 20:37:31]]></Time>
<TimeTick>1476716851</TimeTick>
<NodeArgs eType="General" icon="33" nRep="96" >
<Disp><![CDATA["M":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA["M":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[17-Oct-16 - 20:37:31]]></Time>
<TimeTick>1476716851</TimeTick>
<NodeArgs eType="General" icon="33" nRep="98" >
<Disp><![CDATA["M":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA["M":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[17-Oct-16 - 20:37:31]]></Time>
<TimeTick>1476716851</TimeTick>
<NodeArgs eType="General" icon="33" nRep="100" >
<Disp><![CDATA["M":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA["M":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[ChildItem]]></Details>
<Time><![CDATA[17-Oct-16 - 20:37:31]]></Time>
<TimeTick>1476716851</TimeTick>
<NodeArgs eType="General" icon="33" nRep="102" >
<Disp><![CDATA["M":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[[ 17 ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[17-Oct-16 - 20:37:31]]></Time>
<TimeTick>1476716851</TimeTick>
<NodeArgs eType="Replay" icon="34" nRep="104" Source="Action1" SourceLine="66" >
<Disp><![CDATA[[ 17 ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[adults.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[17-Oct-16 - 20:37:31]]></Time>
<TimeTick>1476716851</TimeTick>
<NodeArgs eType="Replay" icon="35" nRep="106" Source="Action1" SourceLine="66" >
<Disp><![CDATA[adults.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[adults.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["2"]]></Details>
<Time><![CDATA[17-Oct-16 - 20:37:32]]></Time>
<TimeTick>1476716852</TimeTick>
<NodeArgs eType="Replay" icon="35" nRep="109" Source="Action1" SourceLine="66" >
<Disp><![CDATA[adults.Select]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="28" nRep="85" status="Passed" Source="Action1" SourceLine="66" >
<Disp><![CDATA[Cleartrip - Flights, Hotels,]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="26" nRep="84" status="Passed" Source="Action1" SourceLine="66" >
<Disp><![CDATA[Cleartrip - Flights, Hotels,]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj ><![CDATA[Step-2]]></Obj>
<Details ><![CDATA[Flight details page is open]]></Details>
<Time><![CDATA[17-Oct-16 - 20:37:32]]></Time>
<TimeTick>1476716852</TimeTick>
<NodeArgs eType="User" icon="25" nRep="110" status="Passed" >
<Disp><![CDATA[Step-2]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf2.xml]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[Cleartrip - Flights, Hotels,]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[17-Oct-16 - 20:37:32]]></Time>
<TimeTick>1476716852</TimeTick>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[Cleartrip - Flights, Hotels,]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[17-Oct-16 - 20:37:32]]></Time>
<TimeTick>1476716852</TimeTick>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[Search flights.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[17-Oct-16 - 20:37:32]]></Time>
<TimeTick>1476716852</TimeTick>
<NodeArgs eType="Replay" icon="36" nRep="115" Source="Action1" SourceLine="66" >
<Disp><![CDATA[Search flights.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[Flight_details]]></Obj>
<Details plainTxt="False" ><![CDATA[Transaction "Flight_details" ended with "Fail" status (Total Duration: 23.0613 sec Wasted Time: 0.4100 sec).]]></Details>
<Time><![CDATA[17-Oct-16 - 20:37:32]]></Time>
<TimeTick>1476716852</TimeTick>
<NodeArgs eType="Transaction" icon="24" nRep="116" status="Warning" nType="End Transaction" Source="Action1" SourceLine="66" >
<Disp><![CDATA[Flight_details]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[Flight_booking]]></Obj>
<Details plainTxt="False" ><![CDATA[Transaction "Flight_booking" started.]]></Details>
<Time><![CDATA[17-Oct-16 - 20:37:48]]></Time>
<TimeTick>1476716868</TimeTick>
<NodeArgs eType="Transaction" icon="22" nRep="117" nType="Start Transaction" Source="Action1" SourceLine="66" >
<Disp><![CDATA[Flight_booking]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[[ GoAir  ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[17-Oct-16 - 20:37:54]]></Time>
<TimeTick>1476716874</TimeTick>
<NodeArgs eType="Replay" icon="31" nRep="156" Source="Action1" SourceLine="66" >
<Disp><![CDATA[[ GoAir  ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[[ IndiGo  ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[17-Oct-16 - 20:37:54]]></Time>
<TimeTick>1476716874</TimeTick>
<NodeArgs eType="Replay" icon="31" nRep="158" Source="Action1" SourceLine="66" >
<Disp><![CDATA[[ IndiGo  ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA[[ Jet Airways  ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[17-Oct-16 - 20:37:54]]></Time>
<TimeTick>1476716874</TimeTick>
<NodeArgs eType="Replay" icon="31" nRep="160" Source="Action1" SourceLine="66" >
<Disp><![CDATA[[ Jet Airways  ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA[[ GoAir ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[17-Oct-16 - 20:37:55]]></Time>
<TimeTick>1476716875</TimeTick>
<NodeArgs eType="Replay" icon="31" nRep="162" Source="Action1" SourceLine="66" >
<Disp><![CDATA[[ GoAir ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA[[ IndiGo ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[17-Oct-16 - 20:37:55]]></Time>
<TimeTick>1476716875</TimeTick>
<NodeArgs eType="Replay" icon="31" nRep="164" Source="Action1" SourceLine="66" >
<Disp><![CDATA[[ IndiGo ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[[ Jet Airways ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[17-Oct-16 - 20:37:55]]></Time>
<TimeTick>1476716875</TimeTick>
<NodeArgs eType="Replay" icon="31" nRep="166" Source="Action1" SourceLine="66" >
<Disp><![CDATA[[ Jet Airways ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T56">
<Obj plainTxt="False" ><![CDATA[[ Air India  ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[17-Oct-16 - 20:37:55]]></Time>
<TimeTick>1476716875</TimeTick>
<NodeArgs eType="Replay" icon="31" nRep="169" Source="Action1" SourceLine="66" >
<Disp><![CDATA[[ Air India  ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T57">
<Obj plainTxt="False" ><![CDATA[[ Air India  ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[17-Oct-16 - 20:37:56]]></Time>
<TimeTick>1476716876</TimeTick>
<NodeArgs eType="Replay" icon="31" nRep="173" Source="Action1" SourceLine="66" >
<Disp><![CDATA[[ Air India  ].Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="28" nRep="114" status="Warning" Source="Action1" SourceLine="66" >
<Disp><![CDATA[Cleartrip - Flights, Hotels,]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="26" nRep="113" status="Warning" Source="Action1" SourceLine="66" >
<Disp><![CDATA[Cleartrip - Flights, Hotels,]]></Disp>
</NodeArgs>
</Step>
<Step rID="T58">
<Obj ><![CDATA[Step-3]]></Obj>
<Details ><![CDATA[Flight booking is open]]></Details>
<Time><![CDATA[17-Oct-16 - 20:37:56]]></Time>
<TimeTick>1476716876</TimeTick>
<NodeArgs eType="User" icon="25" nRep="176" status="Passed" >
<Disp><![CDATA[Step-3]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf3.xml]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T59">
<Obj plainTxt="False" ><![CDATA[[ Book                                             ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[17-Oct-16 - 20:37:57]]></Time>
<TimeTick>1476716877</TimeTick>
<NodeArgs eType="Replay" icon="36" nRep="179" Source="Action1" SourceLine="66" >
<Disp><![CDATA[[ Book                                             ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T60">
<Obj plainTxt="False" ><![CDATA[Flight_booking]]></Obj>
<Details plainTxt="False" ><![CDATA[Transaction "Flight_booking" ended with "Pass" status (Total Duration: 8.4223 sec).]]></Details>
<Time><![CDATA[17-Oct-16 - 20:37:57]]></Time>
<TimeTick>1476716877</TimeTick>
<NodeArgs eType="Transaction" icon="24" nRep="180" nType="End Transaction" Source="Action1" SourceLine="66" >
<Disp><![CDATA[Flight_booking]]></Disp>
</NodeArgs>
</Step>
<Step rID="T61">
<Obj plainTxt="False" ><![CDATA[Cleartrip - Flights, Hotels,]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[17-Oct-16 - 20:38:00]]></Time>
<TimeTick>1476716880</TimeTick>
<Step rID="T62">