<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step?,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*,Summary,ActionMaintenanceSummary*,NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?)>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="AUS Eastern Standard Time">
<General productName="QuickTest Professional" productVer="10.00" os="" host="WIN-LROHL3BBFAH"><DocLocation><![CDATA[C:\QTP-Hybrid-Framework\TestCases\TC01_CreateOrder]]></DocLocation></General>
<Doc rID="T1"   productName= "QuickTest Professional"  >
<DName><![CDATA[TC01_CreateOrder]]></DName>
<Res><![CDATA[TC01_CreateOrder_30.9.2013_7.5.17]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table">
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action1]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[9/30/2013 - 7:05:26]]></Time>
<TimeTick>1380488726</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Run "C:\Program Files\HP\QuickTest Professional\samples\flight\app\flight4a.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\Program Files\HP\QuickTest Professional\samples\flight\app\flight4a.exe",1]]></Details>
<Time><![CDATA[9/30/2013 - 7:05:26]]></Time>
<TimeTick>1380488726</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="11" status="Passed" Source="C:\QTP-Hybrid-Framework\Resources\AppSpecific_FunctionLibrary\AppSpecific_FunctionLibrary.qfl" SourceLine="7" >
<Disp><![CDATA[Run "C:\Program Files\HP\QuickTest Professional\samples\flight\app\flight4a.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="10" status="Passed" Source="C:\QTP-Hybrid-Framework\Resources\AppSpecific_FunctionLibrary\AppSpecific_FunctionLibrary.qfl" SourceLine="7" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[9/30/2013 - 7:05:26]]></Time>
<TimeTick>1380488726</TimeTick>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[AgentName.SetText]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/30/2013 - 7:05:26]]></Time>
<TimeTick>1380488726</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="14" Source="C:\QTP-Hybrid-Framework\Resources\AppSpecific_FunctionLibrary\AppSpecific_FunctionLibrary.qfl" SourceLine="10" >
<Disp><![CDATA[AgentName.SetText]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj ><![CDATA[Value - 'anish' entered in Field - 'AgentName edit box']]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[9/30/2013 - 7:05:26]]></Time>
<TimeTick>1380488726</TimeTick>
<NodeArgs eType="User" icon="8" nRep="15" status="Passed" Source="C:\QTP-Hybrid-Framework\Resources\AppSpecific_FunctionLibrary\AppSpecific_FunctionLibrary.qfl" SourceLine="10" >
<Disp><![CDATA[Value - 'anish' entered in Field - 'AgentName edit box']]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[Password.SetText]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/30/2013 - 7:05:26]]></Time>
<TimeTick>1380488726</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="17" Source="C:\QTP-Hybrid-Framework\Resources\AppSpecific_FunctionLibrary\AppSpecific_FunctionLibrary.qfl" SourceLine="11" >
<Disp><![CDATA[Password.SetText]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj ><![CDATA[Value - 'mercury' entered in Field - 'Password edit box']]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[9/30/2013 - 7:05:26]]></Time>
<TimeTick>1380488726</TimeTick>
<NodeArgs eType="User" icon="8" nRep="18" status="Passed" Source="C:\QTP-Hybrid-Framework\Resources\AppSpecific_FunctionLibrary\AppSpecific_FunctionLibrary.qfl" SourceLine="11" >
<Disp><![CDATA[Value - 'mercury' entered in Field - 'Password edit box']]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[OK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/30/2013 - 7:05:26]]></Time>
<TimeTick>1380488726</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="20" Source="C:\QTP-Hybrid-Framework\Resources\AppSpecific_FunctionLibrary\AppSpecific_FunctionLibrary.qfl" SourceLine="12" >
<Disp><![CDATA[OK.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj ><![CDATA['OK button' Clicked]]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[9/30/2013 - 7:05:26]]></Time>
<TimeTick>1380488726</TimeTick>
<NodeArgs eType="User" icon="8" nRep="21" status="Passed" Source="C:\QTP-Hybrid-Framework\Resources\AppSpecific_FunctionLibrary\AppSpecific_FunctionLibrary.qfl" SourceLine="12" >
<Disp><![CDATA['OK button' Clicked]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="13" status="Passed" Source="C:\QTP-Hybrid-Framework\Resources\AppSpecific_FunctionLibrary\AppSpecific_FunctionLibrary.qfl" SourceLine="10" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[FlightReservation]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[9/30/2013 - 7:05:31]]></Time>
<TimeTick>1380488731</TimeTick>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[FlightReservation.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[9/30/2013 - 7:05:31]]></Time>
<TimeTick>1380488731</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="23" Source="C:\QTP-Hybrid-Framework\Resources\AppSpecific_FunctionLibrary\AppSpecific_FunctionLibrary.qfl" SourceLine="15" >
<Disp><![CDATA[FlightReservation.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj ><![CDATA[Login Successful]]></Obj>
<Details ><![CDATA[Login Successful]]></Details>
<Time><![CDATA[9/30/2013 - 7:05:31]]></Time>
<TimeTick>1380488731</TimeTick>
<NodeArgs eType="User" icon="8" nRep="24" status="Passed" Source="C:\QTP-Hybrid-Framework\Resources\AppSpecific_FunctionLibrary\AppSpecific_FunctionLibrary.qfl" SourceLine="16" >
<Disp><![CDATA[Login Successful]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[DateOfFlight.Type]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/30/2013 - 7:05:31]]></Time>
<TimeTick>1380488731</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="26" Source="C:\QTP-Hybrid-Framework\Resources\AppSpecific_FunctionLibrary\AppSpecific_FunctionLibrary.qfl" SourceLine="32" >
<Disp><![CDATA[DateOfFlight.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj ><![CDATA[Value - '010135' entered in Field - 'DateOfFlight ActiveX object']]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[9/30/2013 - 7:05:32]]></Time>
<TimeTick>1380488732</TimeTick>
<NodeArgs eType="User" icon="8" nRep="27" status="Passed" Source="C:\QTP-Hybrid-Framework\Resources\AppSpecific_FunctionLibrary\AppSpecific_FunctionLibrary.qfl" SourceLine="32" >
<Disp><![CDATA[Value - '010135' entered in Field - 'DateOfFlight ActiveX object']]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[FlyFrom.Select]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/30/2013 - 7:05:32]]></Time>
<TimeTick>1380488732</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="29" Source="C:\QTP-Hybrid-Framework\Resources\AppSpecific_FunctionLibrary\AppSpecific_FunctionLibrary.qfl" SourceLine="33" >
<Disp><![CDATA[FlyFrom.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj ><![CDATA[Value - 'Denver' selected from Drop Down Field - 'FlyFrom list']]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[9/30/2013 - 7:05:32]]></Time>
<TimeTick>1380488732</TimeTick>
<NodeArgs eType="User" icon="8" nRep="30" status="Passed" Source="C:\QTP-Hybrid-Framework\Resources\AppSpecific_FunctionLibrary\AppSpecific_FunctionLibrary.qfl" SourceLine="33" >
<Disp><![CDATA[Value - 'Denver' selected from Drop Down Field - 'FlyFrom list']]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[FlyTo.Select]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/30/2013 - 7:05:32]]></Time>
<TimeTick>1380488732</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="32" Source="C:\QTP-Hybrid-Framework\Resources\AppSpecific_FunctionLibrary\AppSpecific_FunctionLibrary.qfl" SourceLine="34" >
<Disp><![CDATA[FlyTo.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj ><![CDATA[Value - 'Frankfurt' selected from Drop Down Field - 'FlyTo list']]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[9/30/2013 - 7:05:33]]></Time>
<TimeTick>1380488733</TimeTick>
<NodeArgs eType="User" icon="8" nRep="33" status="Passed" Source="C:\QTP-Hybrid-Framework\Resources\AppSpecific_FunctionLibrary\AppSpecific_FunctionLibrary.qfl" SourceLine="34" >
<Disp><![CDATA[Value - 'Frankfurt' selected from Drop Down Field - 'FlyTo list']]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[Flights....Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/30/2013 - 7:05:33]]></Time>
<TimeTick>1380488733</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="35" Source="C:\QTP-Hybrid-Framework\Resources\AppSpecific_FunctionLibrary\AppSpecific_FunctionLibrary.qfl" SourceLine="35" >
<Disp><![CDATA[Flights....Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj ><![CDATA['Flights... button' Clicked]]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[9/30/2013 - 7:05:33]]></Time>
<TimeTick>1380488733</TimeTick>
<NodeArgs eType="User" icon="8" nRep="36" status="Passed" Source="C:\QTP-Hybrid-Framework\Resources\AppSpecific_FunctionLibrary\AppSpecific_FunctionLibrary.qfl" SourceLine="35" >
<Disp><![CDATA['Flights... button' Clicked]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[FlightsTable]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[9/30/2013 - 7:05:33]]></Time>
<TimeTick>1380488733</TimeTick>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[OK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/30/2013 - 7:05:33]]></Time>
<TimeTick>1380488733</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="39" Source="C:\QTP-Hybrid-Framework\Resources\AppSpecific_FunctionLibrary\AppSpecific_FunctionLibrary.qfl" SourceLine="38" >
<Disp><![CDATA[OK.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj ><![CDATA['OK button' Clicked]]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[9/30/2013 - 7:05:33]]></Time>
<TimeTick>1380488733</TimeTick>
<NodeArgs eType="User" icon="8" nRep="40" status="Passed" Source="C:\QTP-Hybrid-Framework\Resources\AppSpecific_FunctionLibrary\AppSpecific_FunctionLibrary.qfl" SourceLine="38" >
<Disp><![CDATA['OK button' Clicked]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="38" status="Passed" Source="C:\QTP-Hybrid-Framework\Resources\AppSpecific_FunctionLibrary\AppSpecific_FunctionLibrary.qfl" SourceLine="38" >
<Disp><![CDATA[FlightsTable]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[[ Name: ].SetText]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/30/2013 - 7:05:33]]></Time>
<TimeTick>1380488733</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="42" Source="C:\QTP-Hybrid-Framework\Resources\AppSpecific_FunctionLibrary\AppSpecific_FunctionLibrary.qfl" SourceLine="41" >
<Disp><![CDATA[[ Name: ].SetText]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj ><![CDATA[Value - 'anish pillai' entered in Field - '[ Name: ] edit box']]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[9/30/2013 - 7:05:33]]></Time>
<TimeTick>1380488733</TimeTick>
<NodeArgs eType="User" icon="8" nRep="43" status="Passed" Source="C:\QTP-Hybrid-Framework\Resources\AppSpecific_FunctionLibrary\AppSpecific_FunctionLibrary.qfl" SourceLine="41" >
<Disp><![CDATA[Value - 'anish pillai' entered in Field - '[ Name: ] edit box']]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[[ First ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/30/2013 - 7:05:33]]></Time>
<TimeTick>1380488733</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="45" Source="C:\QTP-Hybrid-Framework\Resources\AppSpecific_FunctionLibrary\AppSpecific_FunctionLibrary.qfl" SourceLine="42" >
<Disp><![CDATA[[ First ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj ><![CDATA['[ First ] radio button' Clicked]]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[9/30/2013 - 7:05:33]]></Time>
<TimeTick>1380488733</TimeTick>
<NodeArgs eType="User" icon="8" nRep="46" status="Passed" Source="C:\QTP-Hybrid-Framework\Resources\AppSpecific_FunctionLibrary\AppSpecific_FunctionLibrary.qfl" SourceLine="42" >
<Disp><![CDATA['[ First ] radio button' Clicked]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[[ Insert Order ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/30/2013 - 7:05:33]]></Time>
<TimeTick>1380488733</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="48" Source="C:\QTP-Hybrid-Framework\Resources\AppSpecific_FunctionLibrary\AppSpecific_FunctionLibrary.qfl" SourceLine="43" >
<Disp><![CDATA[[ Insert Order ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj ><![CDATA['[ Insert Order ] button' Clicked]]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[9/30/2013 - 7:05:33]]></Time>
<TimeTick>1380488733</TimeTick>
<NodeArgs eType="User" icon="8" nRep="49" status="Passed" Source="C:\QTP-Hybrid-Framework\Resources\AppSpecific_FunctionLibrary\AppSpecific_FunctionLibrary.qfl" SourceLine="43" >
<Disp><![CDATA['[ Insert Order ] button' Clicked]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj ><![CDATA[Flight booked successfully]]></Obj>
<Details ><![CDATA[Order number - 30]]></Details>
<Time><![CDATA[9/30/2013 - 7:05:43]]></Time>
<TimeTick>1380488743</TimeTick>
<NodeArgs eType="User" icon="8" nRep="50" status="Passed" Source="C:\QTP-Hybrid-Framework\Resources\AppSpecific_FunctionLibrary\AppSpecific_FunctionLibrary.qfl" SourceLine="49" >
<Disp><![CDATA[Flight booked successfully]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[FlightReservation.Close]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/30/2013 - 7:05:44]]></Time>
<TimeTick>1380488744</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="52" Source="C:\QTP-Hybrid-Framework\Resources\AppSpecific_FunctionLibrary\AppSpecific_FunctionLibrary.qfl" SourceLine="113" >
<Disp><![CDATA[FlightReservation.Close]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj ><![CDATA['FlightReservation window' closed]]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[9/30/2013 - 7:05:44]]></Time>
<TimeTick>1380488744</TimeTick>
<NodeArgs eType="User" icon="8" nRep="53" status="Passed" Source="C:\QTP-Hybrid-Framework\Resources\AppSpecific_FunctionLibrary\AppSpecific_FunctionLibrary.qfl" SourceLine="113" >
<Disp><![CDATA['FlightReservation window' closed]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="10" nRep="22" status="Passed" Source="C:\QTP-Hybrid-Framework\Resources\AppSpecific_FunctionLibrary\AppSpecific_FunctionLibrary.qfl" SourceLine="15" >
<Disp><![CDATA[FlightReservation]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="9/30/2013 - 7:05:26" eTime="9/30/2013 - 7:05:44" passed="15" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="7" status="Passed" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" status="Passed" >
<Disp><![CDATA[TC01_CreateOrder Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="9/30/2013 - 7:05:24" eTime="9/30/2013 - 7:05:44" passed="15" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Passed" >
<Disp><![CDATA[Test TC01_CreateOrder Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>